CONFIG_SAP_UPSTREAM_REQUIRE_BLE_ENCRYPTION=n
CONFIG_BT_PRIVACY=n
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_BT_RX_STACK_SIZE=12288
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=2048
CONFIG_SHELL_STACK_SIZE=8192
